---
# [ iptables - handlers ]

- name: daemon-reload (iptables)
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart firewall service
  ansible.builtin.systemd:
    name: firewall
    enabled: true
    masked: false
    state: restarted

- name: Reload firewall service
  ansible.builtin.systemd:
    name: firewall
    enabled: true
    masked: false
    state: reloaded
